/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ApiPublicTmpAiRouteImport } from './routes/api/public/tmp-ai'
import { Route as ApiPublicTrackEventRouteImport } from './routes/api/public/track-event'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpAiRoute = ApiPublicTmpAiRouteImport.update({
  id: '/api/public/tmp-ai',
  path: '/api/public/tmp-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackEventRoute = ApiPublicTrackEventRouteImport.update({
  id: '/api/public/track-event',
  path: '/api/public/track-event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clients': typeof ClientsRoute
  '/embed': typeof EmbedRoute
  '/leads': typeof LeadsRoute
  '/api/public/tmp-ai': typeof ApiPublicTmpAiRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clients': typeof ClientsRoute
  '/embed': typeof EmbedRoute
  '/leads': typeof LeadsRoute
  '/api/public/tmp-ai': typeof ApiPublicTmpAiRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/clients': typeof ClientsRoute
  '/embed': typeof EmbedRoute
  '/leads': typeof LeadsRoute
  '/api/public/tmp-ai': typeof ApiPublicTmpAiRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/clients'
    | '/embed'
    | '/leads'
    | '/api/public/tmp-ai'
    | '/api/public/track-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/clients'
    | '/embed'
    | '/leads'
    | '/api/public/tmp-ai'
    | '/api/public/track-event'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/clients'
    | '/embed'
    | '/leads'
    | '/api/public/tmp-ai'
    | '/api/public/track-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ClientsRoute: typeof ClientsRoute
  EmbedRoute: typeof EmbedRoute
  LeadsRoute: typeof LeadsRoute
  ApiPublicTmpAiRoute: typeof ApiPublicTmpAiRoute
  ApiPublicTrackEventRoute: typeof ApiPublicTrackEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp-ai': {
      id: '/api/public/tmp-ai'
      path: '/api/public/tmp-ai'
      fullPath: '/api/public/tmp-ai'
      preLoaderRoute: typeof ApiPublicTmpAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-event': {
      id: '/api/public/track-event'
      path: '/api/public/track-event'
      fullPath: '/api/public/track-event'
      preLoaderRoute: typeof ApiPublicTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ClientsRoute: ClientsRoute,
  EmbedRoute: EmbedRoute,
  LeadsRoute: LeadsRoute,
  ApiPublicTmpAiRoute: ApiPublicTmpAiRoute,
  ApiPublicTrackEventRoute: ApiPublicTrackEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
